# Generated by Django 5.1.7 on 2025-03-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=500)),
                # ('postby', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
