# Generated by Django 5.1.7 on 2025-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meroapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
