# Generated by Django 5.1.7 on 2025-03-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meroapp', '0002_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postby',
            field=models.CharField(default='', max_length=500),
        ),
    ]
